### ISSUE TITLE
Split up core.cljs into separate file / organise this mess somehow.

### ISSUE THREAD

**Issue by paulkoegel** [paulkoegel/omingard#1]
@maxweber, @the-kenny könnt ihr mir da helfen? ich bin ohne objekte verloren nach welchen kriterien man das am besten aufteilt und wie man leiningen die verschiedenen dateien in bestimmter reiheinfolge laden lässt.
bin für jede hilfe sehr dankbar!

(teil des mülls sind überbleibsel des Om tutorials, andere sachen sind nur code, den ich in Lighttable ausprobiert hab. hoffe da könnt ihr drüberhinweglesen)

**Comment by the-kenny** [comment]
Gerne, morgen!
Am 23.07.2014 23:30 schrieb "Paul Wittmann" notifications@github.com:

**Comment by maxweber** [comment]
294 Zeilen für eine Datei ist doch noch in Ordnung :-) Eine Sache die Du z. B. machen könntest, wäre [cljx](https://github.com/lynaghk/cljx) zu benutzen. Damit kannst Du den Teil der pures Clojure ist, in eine cljx Datei packen. Hätte den Vorteil, dass Du Deine Game-Logik auch in einer normalen Clojure REPL ausprobieren / testen könntest. In der cljs Datei kannst Du dann nur das View / ClojureScript-spezifische belassen.

**Comment by the-kenny** [comment]
Sehe ich aehnlich - 300 Zeilen sind nicht viel. Man _koennte_ UI und Logik voneinander trennen, und Logik eventuell auch noch in eine cljx auslagern, wie Max sagte. Allerdings hast du in lighttable ja eh einen halbwegs guten Cljs-REPL, da lohnt sich der Aufwand vermutlich nicht.

Allerdings wuerde ich zumindest in der Datei Logik klar von UI trennen. Oben die Game-Logik (und alle Funktionen, die dazu gehoeren), dann die Funktionen fuer die UI, erst dann ein Atom fuer den State. 

Die Spiellogik selber sollte nie ein Atom nutzen, sondern immer nur Daten rein -> Daten raus.

**Comment by paulkoegel** [comment]
dank euch. aber ich brauch doch nicht extra cljx um spiellogik vom frontend zu trennen, oder? der code soll ja nur im client (JavaScript) laufen.

was macht man wenn's doch mal mehr zeilen werden? namespaces erstellen für zuständigkeitsbereiche?

könnt gern mal den code n bisschen kommentieren was ihr besser machen würdet. alles hilft! hat zeit. dank euch!

**Comment by paulkoegel** [comment]
FYI, sowas wollte ich: https://github.com/paulwittmann/omingard/pull/12
hab's mir bei goya abgeschaut wie ich dateien in anderen reinlad - mir hat das einfach gefehlt.
der branch diff is n bissl unübersichtlich.
clojure advanced compilation klappt, aber die whitespace compilation komischerweise nicht. habt ihr da ne idee? is nicht wichtig, da ich eh nur advanced will :)
